# Generated by Django 4.2.20 on 2025-05-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ColvaApi', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.IntegerField(default=1, verbose_name='Estado'),
        ),
    ]
